--===========
--FUNCTIONS--
--===========
--========================
--SINGLE ROW FUNCTION
--1.STRING FUNCTION
--2.NUMERIC FUNCTION
--3.DATA AND TIME FUNCTION
--4.NULL FUNCTION
--===========================

--===========================
--1.STRING FUNCTION
--A.MANIPULATE 
--B.CALCULATE
--C.STRING EXTRACTION
--==============================

--SHOW A LIST OF EMPLOYEE'S FIRST NAME TOGETHER WITH THEIR SALARY IN ONE COLUMN

SELECT 
EMP_NAME
,SALARY
,CONCAT (EMP_NAME,' -', SALARY) AS EMP_SALARY
,UPPER (EMP_NAME ) AS UPPER_CASE_NAME
,LOWER(EMP_NAME) AS LOWER_CASE_NAME
FROM EMPLOYEE;

--TRIM --REMOVE LEADING SPACE 
SELECT 
EMP_NAME
,LEN(EMP_NAME) AS TOTAL_LEN
,LEN(TRIM(EMP_NAME)) AS AFTER_TRIM
,LEN(EMP_NAME) - LEN(TRIM(EMP_NAME)) AS FLAG
FROM EMPLOYEE
WHERE LEN(EMP_NAME) != (LEN(TRIM(EMP_NAME)))

--REPLACE
SELECT 
'123-1243-345-90' AS PHONE_NUMBER
,REPLACE('123-1243-345-90', '-' ,'') AS CLEAN_PHONE_NUMBER;

--RETRIVE ALL THE CHARACTER AFTER REMOVING FIRST CHARACTER
SELECT 
EMP_NAME
,SUBSTRING(EMP_NAME, 2 , LEN(EMP_NAME)) AS SUB_NAME
FROM EMPLOYEE;

--NUMBER FUNCTINOS
--ROUND

SELECT 
3.521 AS WITHOUT_ROUND
,ROUND(3.521,2) AS ROUND_VALUE_2
,ROUND(3.521,1) AS ROUND_VALUE_1
,ROUND(3.521,0) AS ROUND_VALUE_0;

--ABScro
 
SELECT
-10
,ABS(-10)







