USE SHUBHAM
GO
--==============
--SET OPERATION
--==============

--UNION , UNION ALL  ,EXCEPT AND INTERSECT 

--========
--UNION
--========
SELECT  EMP_NAME FROM EMPLOYEE
UNION 
SELECT DEPT_ID FROM DEPARTMENT;

--=========
--UNION ALL
--=========

SELECT  EMP_NAME FROM EMPLOYEE
UNION ALL
SELECT DEPT_ID FROM DEPARTMENT;

--=========
--EXCEPT
--=========
SELECT  EMP_NAME FROM EMPLOYEE
EXCEPT
SELECT DEPT_ID FROM DEPARTMENT;

--=========
--INTERSECT
--=========

SELECT  EMP_NAME FROM EMPLOYEE
INTERSECT
SELECT DEPT_ID FROM DEPARTMENT;

--COMBINING THE TWO TABLES TWO SHOW THE DATA
SELECT 
'DEPARTMENT' AS SORCE_TABLE
,[DEPT_ID]
,[DEPT_NAME]
,[DEPT_CENTER]
FROM DEPARTMENT
UNION
SELECT
'MANAGER' AS SORCETAB_LE
,[MANAGER_ID]
,[MANAGER_NAME]
,[DEPT_ID]
FROM MANAGER
ORDER BY DEPT_ID
